default: &default
  adapter: postgresql
  user: David 
  password:
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  host: localhost
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: "development"

test:
  <<: *default
  database: "test"

production:
  <<: *default
  database: "production"
